services:
  - type: web
    name: endoskin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 4 --timeout 120 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: MONGODB_URI
        description: MongoDB connection string
      - key: PYTHON_VERSION
        value: 3.9.13
    healthCheckPath: /
